### ISSUE TITLE
Snap zones should have a means of enabling/disabling

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot-vr-common#183]
Snap zones should have the ability to be enabled or disabled .

**Comment by Henodude** [comment]
If you disabled a snap zone with an object in it, would you not be able to remove the object until it is re-enabled, or would it drop the object? Either way, it would be very useful.

**Comment by Malcolmnixon** [comment]
I figure it would lock currently snapped objects in place preventing removal - the developer could choose to manually drop the object before disabling.

**Comment by DigitalN8m4r3** [comment]
As i see it, the main purpose for this would be for inventorys such as backpacks that can be carried and from my own experience as in trial and failure, this addition would be verry welcome

When a multiple snapzone comtainer is disabled, it would prevent the player from accidently reaching into the backpack when its not currently the held object

**Comment by Malcolmnixon** [comment]
There is a workaround by setting the snap_require and grab_require values to some unused group.
