### ISSUE TITLE
CTD when teleport target meets Trimesh collision

### ISSUE THREAD

**Issue by Sukasa** [GodotVR/godot-vr-common#5]
Godot version: Godot 3.0.6.stable.official.8314054 (Steam vers)
OS: Win10 1803, x64
HMD: HTC Vive

When trying to teleport around, if the teleport ray collides with a trimesh collision shape (e.g. from Mesh->Create Trimesh Collision Sibling), the game closes, with no error message present in the Godot output.

**Comment by BastiaanOlij** [comment]
Weird, I'll find some time to reproduce it, hopefully it's an easy fix. Haven't touched 3.0.6 in awhile :)

**Comment by BastiaanOlij** [comment]
It's worth trying this again with a new master build of Godot. There were issues with the bullet physics when bullet debug mode was on.

**Comment by BastiaanOlij** [comment]
I have been using teleport successfully for a few months now in my weapons tutorial, I think this issue was fixed upstream, it is definitely working fine in 3.1
